# 此文件定义了一些参数

# 预处理
MEDIAN_BLUR_SIZE = 7
PYR_MEAN_SHIFT_FILTERING_SP = 10
PYR_MEAN_SHIFT_FILTERING_SR = 10

# 梯度检测
GRAD_VALID_THRESHOLD = 1
RANGE_MIN = -10
RANGE_MAX = 5
GRAD_GROUP_SIZE = 5
GRAD_GROUP_THRESHOLD = 10

# 晕环检测
DELTA_ANGLE = 6
GROUP_SIZE = 3
MIN_VALID_THRESHOLD = 3
DEVIATION_THRESHOLD = 0.3
